### ISSUE TITLE
Face recognition Error

### ISSUE THREAD

**Issue by masgh21** [TiagoSanti/FaceRecognition#2]
Hello
I compared two similar faces ,
but it got this error ,
they are different person .
Can you help me ?

My code :

var match = FaceRecognition.CompareFace(FaceRecognition.LoadFaceEncoding(Face1), FaceRecognition.LoadFaceEncoding(Face2), 0.6);

my faces are here :
face1
https://pasteboard.co/47Voil1zyrSk.jpg
face2
https://pasteboard.co/XJt2cvEFEenn.jpg

**Comment by TiagoSanti** [comment]
Issue moved because UltraFaceRecognition project no longer implements FaceRecognitionDotNet API and this repository is focused on FRDotNet API exploration.

First of all, you need to give me more details about your code and it's errors so I can understand where is the conflict. But I can anticipate a tip for you if it's a compiling error:
- Check API's requirements on its example's [Readme](https://github.com/takuya-takeuchi/FaceRecognitionDotNet/tree/master/examples/FaceDetection#1-preparation).
- Check if Face1 and Face2 are double array type representing those faces encodings. See [LoadFaceEncoding](https://taktak.jp/FaceRecognitionDotNet/api/FaceRecognitionDotNet.FaceRecognition.html#FaceRecognitionDotNet_FaceRecognition_LoadFaceEncoding_System_Double___) and [CompareFaces](https://taktak.jp/FaceRecognitionDotNet/api/FaceRecognitionDotNet.FaceRecognition.html#FaceRecognitionDotNet_FaceRecognition_CompareFaces_System_Collections_Generic_IEnumerable_FaceRecognitionDotNet_FaceEncoding__FaceRecognitionDotNet_FaceEncoding_System_Double_) methods documentation. 

Show the debug output so I can improve my supporting, please.
